import { ServiceData } from "../types";

const data: ServiceData = {
	songs: {
		ThereIsAGreenHill: {
			title: "There is a Green Hill",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"There is a green hill far away,",
					"Outside a city wall,",
					"Where the dear Lord was crucified,",
					"Who died to save us all.",
				],
				[
					"We may not know, we cannot tell",
					"What pains He had to bear,",
					"But we believe it was for us",
					"He hung and suffered there.",
				],
				[
					"He died that we might be forgiven,",
					"He died to make us good,",
					"That we might go at last to heaven,",
					"Saved by His precious blood.",
				],
				[
					"There was no other good enough",
					"To pay the price of sin,",
					"He only could unlock the gate",
					"Of heaven and let us in.",
				],
				[
					"Oh, dearly, dearly has He loved!",
					"And we must love Him too",
					"And trust in His redeeming blood",
					"And try His works to do.",
				],
			],
			order: "v1 v2 v3 v4 v5",
			copyright: "Public Domain",
			ccli: false,
		},
		HereIsLoveVastAsTheOcean: {
			title: "Here is love, vast as the ocean",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Here is love, vast as the ocean,",
					"loving kindness as the flood:",
					"when the Prince of Life, our Ransom,",
					"shed for us His precious blood.",
					"Who His love will not remember?",
					"Who can cease to sing His praise?",
					"He can never be forgotten",
					"throughout heaven's eternal days.",
				],
				[
					"On the mount of crucifixion",
					"fountains opened deep and wide;",
					"through the floodgates of God's mercy",
					"flowed a vast and gracious tide.",
					"Grace and love, like mighty rivers,",
					"poured incessant from above,",
					"and heaven's peace and perfect justice",
					"kissed a guilty world in love.",
				],
			],
			order: "v1 v2",
			copyright: "Public Domain",
			ccli: false,
		},
		WhenISurveyTheWondrousCross: {
			title: "When I Survey the Wondrous Cross",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"When I survey the wondrous cross",
					"on which the Prince of glory died,",
					"my richest gain I count but loss,",
					"and pour contempt on all my pride.",
				],
				[
					"Forbid it, Lord, that I should boast",
					"save in the death of Christ, my God!",
					"All the vain things that charm me most,",
					"I sacrifice them through his blood.",
				],
				[
					"See, from his head, his hands, his feet,",
					"sorrow and love flow mingled down.",
					"Did e'er such love and sorrow meet,",
					"or thorns compose so rich a crown?",
				],
				[
					"Were the whole realm of nature mine,",
					"that were a present far too small.",
					"Love so amazing, so divine,",
					"demands my soul, my life, my all.",
				],
			],
			order: "v1 v2 v3 v4",
			copyright: "Public Domain",
			ccli: false,
		},
		LordsPrayer: {
			title: "The Lord's Prayer",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Our Father, who art in heaven,",
					"hallowed be thy name;",
					"thy kingdom come;",
					"thy will be done;",
					"on earth as it is in heaven.",
					"Give us this day our daily bread.",
					"And forgive us our trespasses,",
					"as we forgive those who trespass against us.",
					"And lead us not into temptation;",
					"but deliver us from evil.",
					"For thine is the kingdom,",
					"the power and the glory,",
					"for ever and ever.",
					"Amen.",
				],
			],
			order: "v1",
			copyright: "Public Domain",
			ccli: false,
		},
	},
	readings: [
		{
			title: "Matthew 27:32-40",
			subtitle: "The crucifixion of Jesus",
			reading: [
				"As they were going out, they met a man from Cyrene, named Simon, and they forced him to carry the cross. They came to a place called Golgotha (which means ‘the place of the skull’). There they offered Jesus wine to drink, mixed with gall; but after tasting it, he refused to drink it. When they had crucified him, they divided up his clothes by casting lots. And sitting down, they kept watch over him there. Above his head they placed the written charge against him: THIS IS JESUS, THE KING OF THE JEWS.",
				"Two rebels were crucified with him, one on his right and one on his left.  Those who passed by hurled insults at him, shaking their heads and saying, ‘You who are going to destroy the temple and build it in three days, save yourself! Come down from the cross, if you are the Son of God!’",
			],
			copyright:
				"1979, 1984, 2011 by Biblica, Inc., New International Version Anglicized",
		},
		{
			title: "Matthew 27:45-56",
			subtitle: "The death of Jesus",
			reading: [
				"From noon until three in the afternoon darkness came over all the land. About three in the afternoon Jesus cried out in a loud voice, ‘Eli, Eli, lema sabachthani?’ (which means ‘My God, my God, why have you forsaken me?’).",
				"When some of those standing there heard this, they said, ‘He’s calling Elijah.’",
				"Immediately one of them ran and got a sponge. He filled it with wine vinegar, put it on a staff, and offered it to Jesus to drink. The rest said, ‘Now leave him alone. Let’s see if Elijah comes to save him.’",
				"And when Jesus had cried out again in a loud voice, he gave up his spirit.",
				"At that moment the curtain of the temple was torn in two from top to bottom. The earth shook, the rocks split and the tombs broke open. The bodies of many holy people who had died were raised to life. They came out of the tombs after Jesus’ resurrection and went into the holy city and appeared to many people.",
				"When the centurion and those with him who were guarding Jesus saw the earthquake and all that had happened, they were terrified, and exclaimed, ‘Surely he was the Son of God!’",
				"Many women were there, watching from a distance. They had followed Jesus from Galilee to care for his needs. 56 Among them were Mary Magdalene, Mary the mother of James and Joseph, and the mother of Zebedee’s sons.",
			],
			copyright:
				"1979, 1984, 2011 by Biblica, Inc., New International Version Anglicized",
		},
		{
			title: "Matthew 27:57-60",
			subtitle: "The burial of Jesus",
			reading: [
				"As evening approached, there came a rich man from Arimathea, named Joseph, who had himself become a disciple of Jesus. Going to Pilate, he asked for Jesus’ body, and Pilate ordered that it be given to him. Joseph took the body, wrapped it in a clean linen cloth, and placed it in his own new tomb that he had cut out of the rock. He rolled a big stone in front of the entrance to the tomb and went away.",
			],
			copyright:
				"1979, 1984, 2011 by Biblica, Inc., New International Version Anglicized",
		},
	],
	order: [
		{
			type: "title",
			title: "Good Friday 2026",
			subtitle: "with Dunchurch Churches Together",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Reflection at the Canadian Airmen Memorial",
			subtitle: "",
			showOrder: "",
			id: "",
		},
		{
			type: "reading",
			id: "1",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Prayer",
			subtitle: "Rev Ali Jones",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Procession to the War Memorial",
			subtitle: "(please be silent on the walk)",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Welcome",
			subtitle: "Rev Ali Jones",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Prayer",
			subtitle: "Rev Ian Sweeney",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "ThereIsAGreenHill",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "2",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Address",
			subtitle: "Rev Ali Jones",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "HereIsLoveVastAsTheOcean",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Prayers",
			subtitle: "Rev. Ali Jones",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "WhenISurveyTheWondrousCross",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "3",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Blessing",
			subtitle: "",
			showOrder: "",
			id: "",
		},
	],
};
export default data;
