import { ServiceData } from "../types";

const data: ServiceData = {
	songs: {
		OLittleTownOfBethlehem: {
			title: "O Little Town of Bethlehem",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"O little town of Bethlehem,",
					"how still we see thee lie!",
					"Above thy deep and",
					"dreamless sleep",
					"the silent stars go by;",
					"yet in thy dark streets shineth",
					"the everlasting light;",
					"the hopes and fears of all the years",
					"are met in thee tonight.",
				],
				[
					"O morning stars, together",
					"proclaim the holy birth,",
					"and praises sing to God the King",
					"and peace to all on earth.",
					"For Christ is born of Mary",
					"and, gathered all above,",
					"while mortals sleep, the angels keep",
					"their watch of wondering love.",
				],
				[
					"How silently, how silently,",
					"the wondrous gift is given!",
					"So God imparts to human hearts",
					"the blessings of his heaven.",
					"No ear may hear his coming,",
					"but in this world of sin,",
					"where meek souls will receive Him, still",
					"the dear Christ enters in.",
				],
				[
					"O holy child of Bethlehem,",
					"descend to us, we pray;",
					"cast out our sin and enter in,",
					"be born in us today.",
					"We hear the Christmas angels",
					"the great glad tidings tell;",
					"O come to us, abide with us,",
					"our Lord Immanuel.",
				],
			],
			order: "v1 v2 v3 v4",
			copyright: "Public Domain",
			ccli: false,
		},

		SeeAmidTheWintersSnow: {
			title: "See, Amid the Winter's Snow",
			B: [[""]],
			C: [
				[
					"Hail, thou ever-blessed morn!",
					"Hail, redemption’s happy dawn!",
					"Sing through all Jerusalem,",
					"Christ is born in Bethlehem!",
				],
			],
			E: [[""]],
			V: [
				[
					"See, amid the winter’s snow",
					"Born for us on earth below,",
					"See, the Lamb of God appears,",
					"Promised from eternal years.",
				],
				[
					"Lo, within a manger lies",
					"He who built the starry skies,",
					"He who, throned in height sublime,",
					"Sits amid the cherubim.",
				],
				[
					"As we watched at dead of night,",
					"Lo, we saw a wondrous light:",
					"Angels singing, “Peace on earth”",
					"Told us of the Saviour’s birth.",
				],
				[
					"Sacred infant, all divine,",
					"What a tender love was Thine,",
					"Thus to come from highest bliss",
					"Down to such a world as this!",
				],
			],
			order: "v1 c1 v2 c1 v3 c1 v4 c1",
			copyright: "Public Domain",
			ccli: false,
		},

		LittleDonkey: {
			title: "Little Donkey",
			B: [
				[
					"Ring out those bells tonight",
					"Bethlehem, Bethlehem",
					"Follow that star tonight",
					"Bethlehem, Bethlehem",
				],
			],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Little Donkey, Little Donkey",
					"On a dusty road",
					"Got to keep on plodding onward",
					"With your precious load",
				],
				[
					"Been a long time, little donkey,",
					"Through the winter’s night,",
					"Don’t give up now, little donkey,",
					"Bethlehem’s in sight.",
				],
				[
					"Little donkey, little donkey",
					"Had a heavy day",
					"Little donkey",
					"Carry Mary safely on her way",
				],
			],
			order: "v1 v2 b1 v3",
			copyright: "1959 Warner/Chappell Music Ltd",
			ccli: false,
		},

		OnceInRoyalDavidsCity: {
			title: "Once in Royal David's City",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Once in Royal David’s City,",
					"Stood a lowly cattle shed,",
					"Where a mother laid her baby",
					"In a manger for His bed.",
					"Mary was that mother mild",
					"Jesus Christ her little child.",
				],
				[
					"He came down to earth from heaven,",
					"Who is God and Lord of all;",
					"And His shelter was a stable,",
					"And His cradle was a stall:",
					"With the poor, and mean, and lowly",
					"Lived on earth our Saviour holy.",
				],
				[
					"For He is our childhood’s pattern:",
					"Day by day like us He grew;",
					"He was little, weak and helpless,",
					"Tears and smiles like us He knew;",
					"And He feels for all our sadness,",
					"And He shares in all our gladness.",
				],
				[
					"And our eyes at last shall see Him,",
					"Through His own redeeming love;",
					"For that child so dear and gentle,",
					"Is our Lord in heav'n above;",
					"And He leads his children on",
					"To the place where He is gone.",
				],
			],
			order: "v1 v2 v3 v4",
			copyright: "Public Domain",
			ccli: false,
		},

		SilentNight: {
			title: "Silent Night",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Silent Night, holy night,",
					"All is calm, all is bright;",
					"Round yon virgin mother and child,",
					"Holy infant, so tender and mild.",
					"Sleep in heavenly peace,",
					"Sleep in heavenly peace.",
				],
				[
					"Silent night, holy night,",
					"Shepherds quake at the sight;",
					"Glories stream from heaven afar,",
					"Heavenly hosts sing Alleluia.",
					"Christ the Saviour is born,",
					"Christ the Saviour is born.",
				],
				[
					"Silent Night, holy night,",
					"Son of God, love’s pure light;",
					"Radiant beams Thy holy face,",
					"With the dawn of redeeming grace.",
					"Jesus, Lord, at Thy birth,",
					"Jesus, Lord, at Thy birth.",
				],
			],
			order: "v1 v2 v3",
			copyright: "Public Domain",
			ccli: false,
		},

		TheFirstNowell: {
			title: "The First Nowell",
			B: [[""]],
			C: [["Nowell, Nowell, Nowell, Nowell,", "Born is the King of Israel."]],
			E: [[""]],
			V: [
				[
					"The first Nowell the angel did say,",
					"Was to certain poor shepherds in fields as they lay;",
					"In fields where they lay keeping their sheep,",
					"On a cold winter’s night that was so deep.",
				],
				[
					"They looked up and saw a star,",
					"Shining in the east, beyond them far,",
					"And to the earth it gave great light,",
					"And so it continued both day and night.",
				],
				[
					"And by the light of that same star,",
					"Three wise men came from country far;",
					"To seek for a king was their intent,",
					"And to follow the star wherever it went.",
				],
				[
					"Then entered in those wise men three",
					"Full reverently on bended knee,",
					"And offered there in His presence,",
					"Their gold, and myrrh, and frankincense.",
				],
			],
			order: "v1 c1 v2 c1 v3 c1 v4 c1",
			copyright: "Public Domain",
			ccli: false,
		},

		HarkTheHerold: {
			title: "Hark, the Herald Angels Sing",
			B: [[""]],
			C: [["Hark! the herald angels sing", "Glory to the new-born King."]],
			E: [[""]],
			V: [
				[
					"Hark! the herald angels sing",
					"Glory to the newborn King;",
					"Peace on earth and mercy mild,",
					"God and sinners reconciled.",
					"Joyful, all ye nations rise,",
					"Join the triumph of the skies;",
					"With the angelic host proclaim,",
					"“Christ is born in Bethlehem”.",
				],
				[
					"Christ, by highest heaven adored",
					"Christ, the everlasting Lord,",
					"Late in time behold Him come,",
					"Offspring of a virgin’s womb.",
					"Veiled in flesh the Godhead see!",
					"Hail, the incarnate Deity!",
					"Pleased as man with men to dwell,",
					"Jesus, our Immanuel.",
				],
				[
					"Hail, the heaven-born Prince of Peace!",
					"Hail, the Sun of Righteousness!",
					"Light and life to all He brings,",
					"Risen with healing in His wings,",
					"Mild He lays His glory by;",
					"Born, that man no more may die;",
					"Born, to raise the sons of earth;",
					"Born, to give them second birth.",
				],
			],
			order: "v1 c1 v2 c1 v3 c1",
			copyright: "Public Domain",
			ccli: false,
		},
	},
	readings: [
		{
			title: "Luke 1:26-38",
			subtitle: "The Birth of Jesus Foretold",
			reading: [
				"In the sixth month of Elizabeth’s pregnancy, God sent the angel Gabriel to Nazareth, a village in Galilee, to a virgin named Mary. She was engaged to be married to a man named Joseph, a descendant of King David. Gabriel appeared to her and said, “Greetings, favored woman! The Lord is with you!”",

				"Confused and disturbed, Mary tried to think what the angel could mean. “Don’t be afraid, Mary,” the angel told her, “for you have found favor with God! You will conceive and give birth to a son, and you will name him Jesus. He will be very great and will be called the Son of the Most High. The Lord God will give him the throne of his ancestor David. And he will reign over Israel forever; his Kingdom will never end!”",
				"Mary asked the angel, “But how can this happen? I am a virgin.”",

				"The angel replied, “The Holy Spirit will come upon you, and the power of the Most High will overshadow you. So the baby to be born will be holy, and he will be called the Son of God. What’s more, your relative Elizabeth has become pregnant in her old age! People used to say she was barren, but she has conceived a son and is now in her sixth month. For the word of God will never fail.”",

				"Mary responded, “I am the Lord’s servant. May everything you have said about me come true.” And then the angel left her.",
			],
			copyright:
				"1996, 2004, 2015 Tyndale House Foundation, New Living Translation",
		},
		{
			title: "Luke 2: 1-7",
			subtitle: "The Birth of Jesus",
			reading: [
				"At that time the Roman emperor, Augustus, decreed that a census should be taken throughout the Roman Empire. (This was the first census taken when Quirinius was governor of Syria.) All returned to their own ancestral towns to register for this census. And because Joseph was a descendant of King David, he had to go to Bethlehem in Judea, David’s ancient home. He traveled there from the village of Nazareth in Galilee. He took with him Mary, to whom he was engaged, who was now expecting a child.",
				"And while they were there, the time came for her baby to be born. She gave birth to her firstborn son. She wrapped him snugly in strips of cloth and laid him in a manger, because there was no lodging available for them.",
			],
			copyright:
				"1996, 2004, 2015 Tyndale House Foundation, New Living Translation",
		},
		{
			title: "Luke 2: 8-14",
			subtitle: "The birth announced by angels",
			reading: [
				"That night there were shepherds staying in the fields nearby, guarding their flocks of sheep. Suddenly, an angel of the Lord appeared among them, and the radiance of the Lord’s glory surrounded them. They were terrified, but the angel reassured them. “Don’t be afraid!” he said. “I bring you good news that will bring great joy to all people. The Savior—yes, the Messiah, the Lord—has been born today in Bethlehem, the city of David! And you will recognize him by this sign: You will find a baby wrapped snugly in strips of cloth, lying in a manger.”",
				"Suddenly, the angel was joined by a vast host of others—the armies of heaven—praising God and saying,",
				"“Glory to God in highest heaven, and peace on earth to those with whom God is pleased.”",
			],
			copyright:
				"1996, 2004, 2015 Tyndale House Foundation, New Living Translation",
		},
		{
			title: "Luke 2:15-20",
			subtitle: "The shepherds find the baby",
			reading: [
				"When the angels had returned to heaven, the shepherds said to each other, “Let’s go to Bethlehem! Let’s see this thing that has happened, which the Lord has told us about.”",
				"They hurried to the village and found Mary and Joseph. And there was the baby, lying in the manger. After seeing him, the shepherds told everyone what had happened and what the angel had said to them about this child. All who heard the shepherds’ story were astonished, but Mary kept all these things in her heart and thought about them often. The shepherds went back to their flocks, glorifying and praising God for all they had heard and seen. It was just as the angel had told them.",
			],
			copyright:
				"1996, 2004, 2015 Tyndale House Foundation, New Living Translation",
		},
		{
			title: "Matthew 2: 1-12",
			subtitle: "The wise men bring their gifts",
			reading: [
				"Jesus was born in Bethlehem in Judea, during the reign of King Herod. About that time some wise men from eastern lands arrived in Jerusalem, asking, “Where is the newborn king of the Jews? We saw his star as it rose, and we have come to worship him.”",
				"King Herod was deeply disturbed when he heard this, as was everyone in Jerusalem. He called a meeting of the leading priests and teachers of religious law and asked, “Where is the Messiah supposed to be born?”",
				"“In Bethlehem in Judea,” they said, “for this is what the prophet wrote:",
				"‘And you, O Bethlehem in the land of Judah, are not least among the ruling cities of Judah, for a ruler will come from you who will be the shepherd for my people Israel.’”",
				"Then Herod called for a private meeting with the wise men, and he learned from them the time when the star first appeared. Then he told them, “Go to Bethlehem and search carefully for the child. And when you find him, come back and tell me so that I can go and worship him, too!”",
				"After this interview the wise men went their way. And the star they had seen in the east guided them to Bethlehem. It went ahead of them and stopped over the place where the child was. When they saw the star, they were filled with joy! They entered the house and saw the child with his mother, Mary, and they bowed down and worshiped him. Then they opened their treasure chests and gave him gifts of gold, frankincense, and myrrh.",
				"When it was time to leave, they returned to their own country by another route, for God had warned them in a dream not to return to Herod.",
			],
			copyright:
				"1996, 2004, 2015 Tyndale House Foundation, New Living Translation",
		},
	],

	order: [
		{
			type: "title",
			title: "Open Air Nativity 2023",
			subtitle: "with Dunchurch Churches Together",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Welcome",
			subtitle: "and Lighting of the tree",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "OLittleTownOfBethlehem",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "1",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "SeeAmidTheWintersSnow",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "2",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Little Donkey",
			subtitle:
				"Sung by Dunchurch Infants and Junior schools.\nPlease join in from verse two.\n(words on next page)",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "LittleDonkey",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Once in Royal David's City",
			subtitle:
				"Sung by Dunchurch Infants and Junior schools.\nPlease join in from verse two.\n(words on next page)",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "OnceInRoyalDavidsCity",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "3",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Joy to the world",
			subtitle: "Dunchurch Voices",
			showOrder: "",
			id: "",
		},
		{
			type: "reading",
			id: "4",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "SilentNight",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "5",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "TheFirstNowell",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Talk",
			subtitle: "by Tony Shaw\n(Dunchurch Baptist Church)",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "HarkTheHerold",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Blessing",
			subtitle: "by Rev Patricia Townshend\n(St. Peter's Church)",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Happy Christmas",
			subtitle: "from Dunchurch Baptist Church\nand St. Peter's Church",
			showOrder: "",
			id: "",
		},
	],
};

export default data;
