import { ServiceData } from "../types";

const data: ServiceData = {
	songs: {
		OLittleTownOfBethlehem: {
			title: "O Little Town of Bethlehem",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"O little town of Bethlehem,",
					"how still we see thee lie!",
					"Above thy deep and",
					"dreamless sleep",
					"the silent stars go by;",
					"yet in thy dark streets shineth",
					"the everlasting light;",
					"the hopes and fears of all the years",
					"are met in thee tonight.",
				],
				[
					"O morning stars, together",
					"proclaim the holy birth,",
					"and praises sing to God the King",
					"and peace to all on earth.",
					"For Christ is born of Mary",
					"and, gathered all above,",
					"while mortals sleep, the angels keep",
					"their watch of wondering love.",
				],
				[
					"How silently, how silently,",
					"the wondrous gift is given!",
					"So God imparts to human hearts",
					"the blessings of his heaven.",
					"No ear may hear his coming,",
					"but in this world of sin,",
					"where meek souls will receive Him, still",
					"the dear Christ enters in.",
				],
				[
					"O holy child of Bethlehem,",
					"descend to us, we pray;",
					"cast out our sin and enter in,",
					"be born in us today.",
					"We hear the Christmas angels",
					"the great glad tidings tell;",
					"O come to us, abide with us,",
					"our Lord Immanuel.",
				],
			],
			order: "v1 v2 v3 v4",
			copyright: "Public Domain",
			ccli: false,
		},
		SeeAmidTheWintersSnow: {
			title: "See, Amid the Winter's Snow",
			B: [[""]],
			C: [
				[
					"Hail, thou ever-blessed morn!",
					"Hail, redemption’s happy dawn!",
					"Sing through all Jerusalem,",
					"Christ is born in Bethlehem!",
				],
			],
			E: [[""]],
			V: [
				[
					"See, amid the winter’s snow",
					"Born for us on earth below,",
					"See, the Lamb of God appears,",
					"Promised from eternal years.",
				],
				[
					"Lo, within a manger lies",
					"He who built the starry skies,",
					"He who, throned in height sublime,",
					"Sits amid the cherubim.",
				],
				[
					"As we watched at dead of night,",
					"Lo, we saw a wondrous light:",
					"Angels singing, “Peace on earth”",
					"Told us of the Saviour’s birth.",
				],
				[
					"Sacred infant, all divine,",
					"What a tender love was Thine,",
					"Thus to come from highest bliss",
					"Down to such a world as this!",
				],
			],
			order: "v1 c1 v2 c1 v3 c1 v4 c1",
			copyright: "Public Domain",
			ccli: false,
		},
		AwayInAManger: {
			title: "Away in a Manger",
			B: [],
			C: [],
			E: [],
			V: [
				[
					"Away in a manger, no crib for a bed",
					"The little Lord Jesus lay down His sweet head.",
					"The stars in the bright sky looked down where He lay,",
					"The little Lord Jesus, asleep on the hay.",
				],
				[
					"The cattle are lowing, the Baby awakes,",
					"But little Lord Jesus, no crying He makes;",
					"I love Thee, Lord Jesus, look down from the sky",
					"And stay by my side until morning is nigh.",
				],
				[
					"Be near me, Lord Jesus, I ask Thee to stay",
					"Close by me forever, and love me, I pray;",
					"Bless all the dear children in Thy tender care,",
					"And take us to Heaven to live with Thee there.",
				],
			],
			order: "v1 v2 v3",
			copyright: "Public Domain",
			ccli: false,
		},
		LittleDonkey: {
			title: "Little Donkey",
			B: [
				[
					"Ring out those bells tonight",
					"Bethlehem, Bethlehem",
					"Follow that star tonight",
					"Bethlehem, Bethlehem",
				],
			],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Little Donkey, Little Donkey",
					"On a dusty road",
					"Got to keep on plodding onward",
					"With your precious load",
				],
				[
					"Been a long time, little donkey,",
					"Through the winter’s night,",
					"Don’t give up now, little donkey,",
					"Bethlehem’s in sight.",
				],
				[
					"Little donkey, little donkey",
					"Had a heavy day",
					"Little donkey",
					"Carry Mary safely on her way",
				],
			],
			order: "v1 v2 b1 v3",
			copyright: "1959 Warner/Chappell Music Ltd",
			ccli: false,
		},
		OnceInRoyalDavidsCity: {
			title: "Once in Royal David's City",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Once in Royal David’s City,",
					"Stood a lowly cattle shed,",
					"Where a mother laid her baby",
					"In a manger for His bed.",
					"Mary was that mother mild",
					"Jesus Christ her little child.",
				],
				[
					"He came down to earth from heaven,",
					"Who is God and Lord of all;",
					"And His shelter was a stable,",
					"And His cradle was a stall:",
					"With the poor, and mean, and lowly",
					"Lived on earth our Saviour holy.",
				],
				[
					"For He is our childhood’s pattern:",
					"Day by day like us He grew;",
					"He was little, weak and helpless,",
					"Tears and smiles like us He knew;",
					"And He feels for all our sadness,",
					"And He shares in all our gladness.",
				],
				[
					"And our eyes at last shall see Him,",
					"Through His own redeeming love;",
					"For that child so dear and gentle,",
					"Is our Lord in heav'n above;",
					"And He leads his children on",
					"To the place where He is gone.",
				],
			],
			order: "v1 v2 v3 v4",
			copyright: "Public Domain",
			ccli: false,
		},
		SilentNight: {
			title: "Silent Night",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"Silent Night, holy night,",
					"All is calm, all is bright;",
					"Round yon virgin mother and child,",
					"Holy infant, so tender and mild.",
					"Sleep in heavenly peace,",
					"Sleep in heavenly peace.",
				],
				[
					"Silent night, holy night,",
					"Shepherds quake at the sight;",
					"Glories stream from heaven afar,",
					"Heavenly hosts sing Alleluia.",
					"Christ the Saviour is born,",
					"Christ the Saviour is born.",
				],
				[
					"Silent Night, holy night,",
					"Son of God, love’s pure light;",
					"Radiant beams Thy holy face,",
					"With the dawn of redeeming grace.",
					"Jesus, Lord, at Thy birth,",
					"Jesus, Lord, at Thy birth.",
				],
			],
			order: "v1 v2 v3",
			copyright: "Public Domain",
			ccli: false,
		},
		TheFirstNowell: {
			title: "The First Nowell",
			B: [[""]],
			C: [["Nowell, Nowell, Nowell, Nowell,", "Born is the King of Israel."]],
			E: [[""]],
			V: [
				[
					"The first Nowell the angel did say,",
					"Was to certain poor shepherds in fields as they lay;",
					"In fields where they lay keeping their sheep,",
					"On a cold winter’s night that was so deep.",
				],
				[
					"Then wise men from a country far",
					"Looked up and saw a guiding star",
					"They travelled on by night and day",
					"To reach the place where Jesus lay.",
				],
				[
					"At Bethlehem they entered in",
					"On bended knee they worshiped Him,",
					"They offered there in his presence",
					"their gold, and myrrh, and frankincense.",
				],
				[
					"Then let us all with one accord",
					"sing praises to our heavenly Lord,",
					"For Christ has our salvation wrought,",
					"and with his blood mankind has bought.",
				],
			],
			order: "v1 c1 v2 c1 v3 c1 v4 c1",
			copyright: "Public Domain",
			ccli: false,
		},
		HarkTheHerald: {
			title: "Hark, the Herald Angels Sing",
			B: [[""]],
			C: [["Hark! the herald angels sing", "Glory to the new-born King."]],
			E: [[""]],
			V: [
				[
					"Hark! the herald angels sing",
					"Glory to the newborn King;",
					"Peace on earth and mercy mild,",
					"God and sinners reconciled.",
					"Joyful, all ye nations rise,",
					"Join the triumph of the skies;",
					"With the angelic host proclaim,",
					"“Christ is born in Bethlehem”.",
				],
				[
					"Christ, by highest heaven adored",
					"Christ, the everlasting Lord,",
					"Late in time behold Him come,",
					"Offspring of a virgin’s womb.",
					"Veiled in flesh the Godhead see!",
					"Hail, the incarnate Deity!",
					"Pleased as man with men to dwell,",
					"Jesus, our Immanuel.",
				],
				[
					"Hail, the heaven-born Prince of Peace!",
					"Hail, the Sun of Righteousness!",
					"Light and life to all He brings,",
					"Risen with healing in His wings,",
					"Mild He lays His glory by;",
					"Born, that man no more may die;",
					"Born, to raise the sons of earth;",
					"Born, to give them second birth.",
				],
			],
			order: "v1 c1 v2 c1 v3 c1",
			copyright: "Public Domain",
			ccli: false,
		},
		AsWithGladness: {
			title: "As With Gladness",
			B: [[""]],
			C: [[""]],
			E: [[""]],
			V: [
				[
					"As with gladness men of old",
					"Did the guiding star behold;",
					"As with joy they hailed its light,",
					"Leading onward, beaming bright,",
					"So, most gracious Lord, may we",
					"Ever more be led to thee.",
				],
				[
					"As with joyful steps they sped,",
					"Savior, to thy lowly bed,",
					"There to bend the knee before",
					"Thee whom Heav’n and Earth adore,",
					"So may we with willing feet",
					"Ever seek thy mercy seat.",
				],
				[
					"As they offered gifts most rare",
					"At thy cradle rude and bare,",
					"So may we with holy joy,",
					"Pure and free from sin’s alloy,",
					"All our costliest treasures bring,",
					"Christ, to thee, our heav’nly King.",
				],
				[
					"Holy Jesus, ev’ry day",
					"Keep us in the narrow way,",
					"And when earthly things are past,",
					"Bring our ransomed souls at last",
					"Where they need no star to guide,",
					"Where no clouds thy glory hide.",
				],
				[
					"In the heav’nly country bright,",
					"Need they no created light;",
					"Thou its light, its joy, its crown,",
					"Thou its sun, which goes not down;",
					"There forever may we sing",
					"Alleluias to our King.",
				],
			],
			order: "v1 v2 v3 v4",
			copyright: "Public Domain",
			ccli: false,
		},
		OComeAllYouFaithful: {
			title: "O Come, All You Faithful",
			B: [[""]],
			C: [
				[
					"O come, let us adore Him;",
					"O come, let us adore Him;",
					"O come, let us adore Him, Christ, the Lord!",
				],
			],
			E: [[""]],
			V: [
				[
					"O come, all you faithful, joyful and triumphant,",
					"O come now, O come now to Bethlehem!",
					"Come, and behold Him, born the King of angels!",
				],
				[
					"True God of true God, light of light eternal,",
					"He, He abhors not the virgin's womb;",
					"Son of the Father, begotten not created;",
				],
				[
					"Sing, choirs of angels; sing in exultation;",
					"Sing, with citizens of heaven above!",
					"Glory to God, glory in the highest!",
				],
			],
			order: "v1 c1 v2 c1 v3 c1",
			copyright: "Public Domain",
			ccli: false,
		},
		JoyToTheWorld: {
			title: "Joy to the World",
			B: [],
			C: [],
			E: [],
			V: [
				[
					"Joy to the world! The Lord is come",
					"Let earth receive her King",
					"Let every heart prepare Him room",
					"And heaven and nature sing",
					"And heaven and nature sing",
					"And heaven, and heaven, and nature sing",
				],
				[
					"Joy to the Earth! The Saviour reigns",
					"Your sweetest songs employ",
					"While fields and floods, and hills, and plains",
					"Repeat the sounding joy",
					"Repeat the sounding joy",
					"Repeat, repeat the sounding joy",
				],
				[
					"He rules the world with truth and grace",
					"And makes the nations prove",
					"The glories of His righteousness",
					"And wonders of His love",
					"And wonders of His love",
					"And wonders, wonders, of His love!",
				],
			],
			order: "v1 v2 v3",
			copyright: "Public Domain",
			ccli: false,
		},
	},
	readings: [
		{
			title: "Luke 1:26-38",
			subtitle: "The Birth of Jesus Foretold",
			reading: [
				"In the sixth month of Elizabeth’s pregnancy, God sent the angel Gabriel to Nazareth, a town in Galilee, to a virgin pledged to be married to a man named Joseph, a descendant of David. The virgin’s name was Mary. The angel went to her and said, ‘Greetings, you who are highly favoured! The Lord is with you.’",
				"Mary was greatly troubled at his words and wondered what kind of greeting this might be. But the angel said to her, ‘Do not be afraid, Mary, you have found favour with God. You will conceive and give birth to a son, and you are to call him Jesus. He will be great and will be called the Son of the Most High. The Lord God will give him the throne of his father David, and he will reign over Jacob’s descendants for ever; his kingdom will never end.’",
				"‘How will this be,’ Mary asked the angel, ‘since I am a virgin?’",
				"The angel answered, ‘The Holy Spirit will come on you, and the power of the Most High will overshadow you. So the holy one to be born will be called the Son of God. Even Elizabeth your relative is going to have a child in her old age, and she who was said to be unable to conceive is in her sixth month. For no word from God will ever fail.’",
				"‘I am the Lord’s servant,’ Mary answered. ‘May your word to me be fulfilled.’ Then the angel left her. ",
			],
			copyright:
				"Holy Bible, New International Version® Anglicized, NIV® Copyright © 1979, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
		},
		{
			title: "Luke 2: 1-7",
			subtitle: "The Birth of Jesus",
			reading: [
				"In those days Caesar Augustus issued a decree that a census should be taken of the entire Roman world. (This was the first census that took place while Quirinius was governor of Syria.) And everyone went to their own town to register.",
				"So Joseph also went up from the town of Nazareth in Galilee to Judea, to Bethlehem the town of David, because he belonged to the house and line of David. He went there to register with Mary, who was pledged to be married to him and was expecting a child. While they were there, the time came for the baby to be born,",
				"and she gave birth to her firstborn, a son. She wrapped him in cloths and placed him in a manger, because there was no guest room available for them.",
			],
			copyright:
				"Holy Bible, New International Version® Anglicized, NIV® Copyright © 1979, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
		},
		{
			title: "Luke 2: 8-14",
			subtitle: "The birth announced by angels",
			reading: [
				"And there were shepherds living out in the fields near by, keeping watch over their flocks at night. An angel of the Lord appeared to them, and the glory of the Lord shone around them, and they were terrified. But the angel said to them, ‘Do not be afraid. I bring you good news that will cause great joy for all the people. Today in the town of David a Saviour has been born to you; he is the Messiah, the Lord. This will be a sign to you: you will find a baby wrapped in cloths and lying in a manger.’",
				"Suddenly a great company of the heavenly host appeared with the angel, praising God and saying,",
				"‘Glory to God in the highest heaven, and on earth peace to those on whom his favour rests.’",
			],
			copyright:
				"Holy Bible, New International Version® Anglicized, NIV® Copyright © 1979, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
		},
		{
			title: "Luke 2:15-20",
			subtitle: "The shepherds find the baby",
			reading: [
				"When the angels had left them and gone into heaven, the shepherds said to one another, ‘Let’s go to Bethlehem and see this thing that has happened, which the Lord has told us about.’",
				"So they hurried off and found Mary and Joseph, and the baby, who was lying in the manger. When they had seen him, they spread the word concerning what had been told them about this child,",
				"and all who heard it were amazed at what the shepherds said to them. But Mary treasured up all these things and pondered them in her heart. The shepherds returned, glorifying and praising God for all the things they had heard and seen, which were just as they had been told.",
			],
			copyright:
				"Holy Bible, New International Version® Anglicized, NIV® Copyright © 1979, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
		},
		{
			title: "Matthew 2: 1-12",
			subtitle: "The wise men bring their gifts",
			reading: [
				"After Jesus was born in Bethlehem in Judea, during the time of King Herod, Magi from the east came to Jerusalem and asked, ‘Where is the one who has been born king of the Jews? We saw his star when it rose and have come to worship him.’",
				"When King Herod heard this he was disturbed, and all Jerusalem with him. When he had called together all the people’s chief priests and teachers of the law, he asked them where the Messiah was to be born. ‘In Bethlehem in Judea,’ they replied, ‘for this is what the prophet has written: ‘“But you, Bethlehem, in the land of Judah, are by no means least among the rulers of Judah; for out of you will come a ruler who will shepherd my people Israel.”’",
				"Then Herod called the Magi secretly and found out from them the exact time the star had appeared. He sent them to Bethlehem and said, ‘Go and search carefully for the child. As soon as you find him, report to me, so that I too may go and worship him.’",
				"After they had heard the king, they went on their way, and the star they had seen when it rose went ahead of them until it stopped over the place where the child was. When they saw the star, they were overjoyed. On coming to the house, they saw the child with his mother Mary, and they bowed down and worshipped him. Then they opened their treasures and presented him with gifts of gold, frankincense and myrrh. And having been warned in a dream not to go back to Herod, they returned to their country by another route.",
			],
			copyright:
				"Holy Bible, New International Version® Anglicized, NIV® Copyright © 1979, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
		},
	],
	order: [
		{
			type: "title",
			title: "Open Air Nativity 2025",
			subtitle: "with Dunchurch Churches Together",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Welcome",
			subtitle: "and Lighting of the tree",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "OComeAllYouFaithful",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "1",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "OLittleTownOfBethlehem",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "2",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Dunchurch Infant School",
			subtitle: "sing 'Away in a Manger'\nPlease join in with verse 3",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "AwayInAManger",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "3",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "JoyToTheWorld",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Prayer",
			subtitle: "Rev Ian Sweeney\n(St Peter's)",
			showOrder: "",
			id: "",
		},
		{
			type: "reading",
			id: "4",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "SilentNight",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "reading",
			id: "5",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "song",
			id: "TheFirstNowell",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Talk",
			subtitle: "by Rev. Ali Jones\n(Dunchurch Baptist)",
			showOrder: "",
			id: "",
		},
		{
			type: "song",
			id: "HarkTheHerald",
			showOrder: "",
			title: "",
			subtitle: "",
		},
		{
			type: "title",
			title: "Blessing",
			subtitle: "by Rev. Ali Jones\n(Dunchurch Baptist)",
			showOrder: "",
			id: "",
		},
		{
			type: "title",
			title: "Happy Christmas",
			subtitle: "from Dunchurch Baptist Church\nand St. Peter's Church",
			showOrder: "",
			id: "",
		},
	],
};

export default data;
